### PR TITLE
categories fixed and CRUD complete

### PR DESCRIPTION
**Pull request by MartyEternal**
A lot was done while you guys were sleeping. I was still hyped from the BOSS coffee I drank, so I got to coding after picking up my friend from his work.

I still don't know what happened for Johnny's code to not work, because I don't remember seeing anything too different to what we've been doing for Cat/Finch collector. I followed the guide perfectly and managed to code in Categories fine. I also fixed Items to keep it in line with our ERD and the code will also make 100% sense (instead of doing  {% for item in inventory %}, it'll now be {% for item in items %}

Everything - I mean EVERYTHING - is working right now. Johnny hasn't tasked anyone with adding a category to an item yet, so I haven't touched that. I'll leave that for him to decide who should do it.

My hands are really cold, but I only felt it now because I'm no longer tense from trying to make sure the code is all correct.

### CODE REVIEW

**Comment by MartyEternal** [comment]
I don't know what happened, but my .gitignore doesn't have anything in it. The one on main branch is the correct one.

**Comment by jackson-07** [comment]
Everything looks good however if I push this to main it will remove all the .gitignore files which we need.

Let's catch up tonight because we might need to create another pull request

**Comment by Exiled184** [comment]
I also reviewed the code, it looks good.

I'm trying to compare it, to the code I wrote yesterday and the only major difference is i left out the items coding in the items/details.html

apologies for last night, I was unable to action and send through my portion of the CRUD. I'll make sure to go over the catcollector/finchcollector stuff before tonight session. I'll assign myself the adding an item to a category

**Comment by jackson-07** [comment]
Going to send this back so we can add the gitignore files back in but good job overall Marty!

**Pull request closed without merging**
